version: '3'
services:
  bike-service:
    image: bike-service:1.0
    ports:
      - "8083"
    deploy:
      replicas: 2
    build:
      context: ./bike-service
    depends_on:
      - api-gateway
    networks:
      - leadyourway-network

  rental-service:
    image: rental-service:1.0
    ports:
      - "8082"
    deploy:
      replicas: 2
    build:
      context: ./rental-service
    depends_on:
      - api-gateway
    networks:
      - leadyourway-network

  payment-service:
    image: payment-service:1.0
    deploy:
      replicas: 2
    build:
      context: ./payment-service
    ports:
      - "8085"
    networks:
      - leadyourway-network

  consultation-service:
    image: consultation-service:1.0
    build:
      context: ./consultation-service
    ports:
      - "8181:8181"
    networks:
      - leadyourway-network

  user-service:
    image: user-service:1.0
    deploy:
      replicas: 2
    build:
      context: ./user-service
    ports:
      - "8084"
    depends_on:
      - api-gateway
    networks:
      - leadyourway-network


  api-gateway:
    image: api-gateway:1.0
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      - leadyourway-network


  service-registry:
    container_name: service-registry
    image: service-registry:1.0
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 20s
      timeout: 10s
      retries: 3
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - leadyourway-network


  config-service:
    container_name: config-service
    image: config-service:1.0
    build: 
      context: ./config-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/healthy/default" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "8888:8888"
    networks:
      - leadyourway-network


networks:
  leadyourway-network:
    driver: bridge

      