server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leadyourway-upc/leadyourway-spring-cloud-config.git
          default-label: main
