server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leadyourway-upc/Spring-cloud-config-LeadYourWay.git
          default-label: main
